// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Use getSession() for the token — getUser() would hit the network on every RPC.
    // Token validity is enforced server-side in requireSupabaseAuth via getClaims().
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (!token) return next({ headers: {} });
    return next({
      headers: { Authorization: `Bearer ${token}` },
    });
  },
)
